export default {
  locale: 'en',
  messages: {
    serial: 'Serial',
    doc: 'Docs',
    device: 'device',
    baudrate: 'baudrate',
    databit: 'databit',
    stopbit: 'stopbit',
    parity: 'parity',
    flowcontrol: 'flow control',
    refresh: 'refresh',
    open: 'open',
    close: 'close',
    opening: 'opening',
    closing: 'closing',
    send: 'send',
    hex: 'Hex',
    middleware: 'middleware',
    preMiddleware: 'pre-middleware',
    postMiddleware: 'post-middleware',
    sendMiddleware: 'send-middleware',
    clear: 'clear',
    loopback: 'loopback',
    displayMode: 'Display Mode',
    rawHex: 'hex',
    rawStr: 'string',
    itemHex: 'hex/frame',
    itemStr: 'string/frame',
    displayNone: 'none',
    scriptSend: 'script',
    append: 'append',
  },
};
