export default {
  locale: 'zh',
  messages: {
    serial: '串口',
    doc: '文档',
    device: '设备',
    baudrate: '波特率',
    databit: '数据位',
    stopbit: '停止位',
    parity: '校验位',
    flowcontrol: '流控制',
    refresh: '刷新',
    open: '打开',
    close: '关闭',
    send: '发送',
    hex: '十六进制',
    middleware: '中间件',
    preMiddleware: '前置中间件',
    postMiddleware: '后置中间件',
    sendMiddleware: '发送中间件',
    clear: '清空',
    loopback: '回送',
    displayMode: '显示模式',
    rawHex: '十六进制',
    rawStr: '字符串',
    itemHex: '十六进制/帧',
    itemStr: '字符串/帧',
    displayNone: '不显示',
    scriptSend: '脚本发送',
    append: '末尾加',
  },
};
